CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discord_id TEXT NOT NULL UNIQUE,
    username TEXT NOT NULL,
    display_name TEXT
);

CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    source_type TEXT NOT NULL,
    channel_name TEXT,
    content TEXT NOT NULL,
    tstamp TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS text_chunks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_name TEXT NOT NULL,
    content TEXT NOT NULL,
    start_at TIMESTAMPTZ NOT NULL,
    end_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT text_chunks_channel_window_unique UNIQUE (channel_name, start_at, end_at)
);

CREATE INDEX IF NOT EXISTS idx_messages_user_id ON messages (user_id);
CREATE INDEX IF NOT EXISTS idx_messages_tstamp ON messages (tstamp);
CREATE INDEX IF NOT EXISTS idx_messages_channel_tstamp ON messages (channel_name, tstamp);
CREATE INDEX IF NOT EXISTS idx_text_chunks_window ON text_chunks (channel_name, start_at, end_at);
