CREATE TABLE IF NOT EXISTS voice_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT NOT NULL,
    voice_channel_id TEXT NOT NULL,
    channel_name TEXT NOT NULL,
    summary_channel_id TEXT,
    started_at TIMESTAMPTZ NOT NULL,
    ended_at TIMESTAMPTZ,
    status TEXT NOT NULL DEFAULT 'open',
    summary TEXT,
    agent_error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE messages ADD COLUMN IF NOT EXISTS session_id BIGINT;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'messages_session_id_fkey'
    ) THEN
        ALTER TABLE messages
        ADD CONSTRAINT messages_session_id_fkey
        FOREIGN KEY (session_id) REFERENCES voice_sessions(id);
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS voice_recordings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT REFERENCES voice_sessions(id),
    recording_filename TEXT NOT NULL UNIQUE,
    discord_id TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'transcribing',
    error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_profiles (
    user_id BIGINT PRIMARY KEY REFERENCES users(id),
    summary TEXT NOT NULL DEFAULT '',
    interests TEXT NOT NULL DEFAULT '',
    communication_style TEXT NOT NULL DEFAULT '',
    known_facts TEXT NOT NULL DEFAULT '',
    recent_updates TEXT NOT NULL DEFAULT '',
    google_doc_id TEXT,
    google_doc_url TEXT,
    last_updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_messages_session_id ON messages (session_id);
CREATE INDEX IF NOT EXISTS idx_voice_sessions_status ON voice_sessions (status);
CREATE INDEX IF NOT EXISTS idx_voice_recordings_session_status ON voice_recordings (session_id, status);
