-- Original speech time remains in tstamp; receipt time keeps late transcripts in a new bulk.
ALTER TABLE messages ADD COLUMN IF NOT EXISTS observed_at TIMESTAMPTZ;
UPDATE messages SET observed_at = tstamp WHERE observed_at IS NULL;
ALTER TABLE messages ALTER COLUMN observed_at SET DEFAULT clock_timestamp();
ALTER TABLE messages ALTER COLUMN observed_at SET NOT NULL;
CREATE INDEX IF NOT EXISTS idx_messages_observed_at ON messages (observed_at);

CREATE TABLE IF NOT EXISTS group_memory_state (
    guild_id TEXT PRIMARY KEY,
    started_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE IF NOT EXISTS group_memory_bulks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT NOT NULL,
    start_at TIMESTAMPTZ NOT NULL,
    end_at TIMESTAMPTZ NOT NULL,
    summary TEXT NOT NULL,
    lore TEXT NOT NULL,
    channel_id TEXT,
    reaction_text TEXT NOT NULL DEFAULT '',
    speak BOOLEAN NOT NULL DEFAULT FALSE,
    gif_query TEXT NOT NULL DEFAULT '',
    reaction_status TEXT NOT NULL DEFAULT 'silent',
    profiled_user_ids BIGINT[] NOT NULL DEFAULT '{}',
    member_ids BIGINT[] NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (guild_id, start_at, end_at)
);
CREATE TABLE IF NOT EXISTS group_memory_messages (
    bulk_id BIGINT NOT NULL REFERENCES group_memory_bulks(id) ON DELETE CASCADE,
    message_id BIGINT PRIMARY KEY REFERENCES messages(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_group_memory_bulks_guild ON group_memory_bulks(guild_id, end_at DESC);
CREATE INDEX IF NOT EXISTS idx_group_memory_messages_bulk ON group_memory_messages(bulk_id);
